// File generated by CPPExt (Enum)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _BRepBuilderAPI_ShellError_HeaderFile
#define _BRepBuilderAPI_ShellError_HeaderFile

//! Indicates the outcome of the construction of a face, i.e. <br>
//! whether it is successful or not, as explained below: <br>
//! -   BRepBuilderAPI_ShellDone No error occurred. <br>
//!   The shell is correctly built. <br>
//! -   BRepBuilderAPI_EmptyShell No initialization of <br>
//!   the algorithm: only an empty constructor was used ; or <br>
//!   the algorithm cannot cut the surface in C2 continuous faces. <br>
//! -   BRepBuilderAPI_DisconnectedShell not yet used <br>
//! -   BRepBuilderAPI_ShellParametersOutOfRange <br>
//!   The parameters given to limit the surface are out of its bounds. <br>
enum BRepBuilderAPI_ShellError { 
 BRepBuilderAPI_ShellDone,
BRepBuilderAPI_EmptyShell,
BRepBuilderAPI_DisconnectedShell,
BRepBuilderAPI_ShellParametersOutOfRange
};


#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
