// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _BRepMesh_HeaderFile
#define _BRepMesh_HeaderFile

#ifndef _Standard_Real_HeaderFile
#include <Standard_Real.hxx>
#endif
class TopoDS_Shape;
class BRepMesh_Vertex;
class BRepMesh_Edge;
class BRepMesh_Triangle;
class BRepMesh_ShapeTool;
class BRepMesh_GeomTool;
class BRepMesh_Delaun;
class BRepMesh_DataMapOfVertexInteger;
class BRepMesh_DataMapOfMeshVertexInteger;
class BRepMesh_DataMapOfIntegerFace;
class BRepMesh_ListOfVertex;
class BRepMesh_ListOfXY;
class BRepMesh_DataMapOfIntegerListOfXY;
class BRepMesh_VertexHasher;
class BRepMesh_IndexedMapOfVertex;
class BRepMesh_DataMapOfCouplePnt;
class BRepMesh_DataMapOfShapeReal;
class BRepMesh_BiPoint;
class BRepMesh_Array1OfBiPoint;
class BRepMesh_Discret;
class BRepMesh_FastDiscret;
class BRepMesh_Classifier;
class BRepMesh_SurfaceGrid;
class BRepMesh_DataMapOfShapeSurfaceGrid;
class BRepMesh_ListOfSurfaceGrid;
class BRepMesh_EdgeDiscret;
class BRepMesh_DataMapOfShapeEdgeDiscret;
class BRepMesh_IncrementalMesh;
class BRepMesh_NodeHasherOfDataStructureOfDelaun;
class BRepMesh_LinkHasherOfDataStructureOfDelaun;
class BRepMesh_ElemHasherOfDataStructureOfDelaun;
class BRepMesh_IndexedDataMapNodeOfIDMapOfNodeOfDataStructureOfDelaun;
class BRepMesh_IDMapOfNodeOfDataStructureOfDelaun;
class BRepMesh_IndexedDataMapNodeOfIDMapOfLinkOfDataStructureOfDelaun;
class BRepMesh_IDMapOfLinkOfDataStructureOfDelaun;
class BRepMesh_IndexedMapNodeOfIMapOfElementOfDataStructureOfDelaun;
class BRepMesh_IMapOfElementOfDataStructureOfDelaun;
class BRepMesh_SelectorOfDataStructureOfDelaun;
class BRepMesh_DataStructureOfDelaun;
class BRepMesh_ComparatorOfVertexOfDelaun;
class BRepMesh_ComparatorOfIndexedVertexOfDelaun;
class BRepMesh_Array1OfVertexOfDelaun;
class BRepMesh_HArray1OfVertexOfDelaun;
class BRepMesh_HeapSortVertexOfDelaun;
class BRepMesh_HeapSortIndexedVertexOfDelaun;
class BRepMesh_DataMapNodeOfDataMapOfVertexInteger;
class BRepMesh_DataMapIteratorOfDataMapOfVertexInteger;
class BRepMesh_DataMapNodeOfDataMapOfMeshVertexInteger;
class BRepMesh_DataMapIteratorOfDataMapOfMeshVertexInteger;
class BRepMesh_DataMapNodeOfDataMapOfIntegerFace;
class BRepMesh_DataMapIteratorOfDataMapOfIntegerFace;
class BRepMesh_ListNodeOfListOfVertex;
class BRepMesh_ListIteratorOfListOfVertex;
class BRepMesh_ListNodeOfListOfXY;
class BRepMesh_ListIteratorOfListOfXY;
class BRepMesh_DataMapNodeOfDataMapOfIntegerListOfXY;
class BRepMesh_DataMapIteratorOfDataMapOfIntegerListOfXY;
class BRepMesh_IndexedMapNodeOfIndexedMapOfVertex;
class BRepMesh_DataMapNodeOfDataMapOfCouplePnt;
class BRepMesh_DataMapIteratorOfDataMapOfCouplePnt;
class BRepMesh_DataMapNodeOfDataMapOfShapeReal;
class BRepMesh_DataMapIteratorOfDataMapOfShapeReal;
class BRepMesh_DataMapNodeOfDataMapOfShapeSurfaceGrid;
class BRepMesh_DataMapIteratorOfDataMapOfShapeSurfaceGrid;
class BRepMesh_ListNodeOfListOfSurfaceGrid;
class BRepMesh_ListIteratorOfListOfSurfaceGrid;
class BRepMesh_DataMapNodeOfDataMapOfShapeEdgeDiscret;
class BRepMesh_DataMapIteratorOfDataMapOfShapeEdgeDiscret;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

//! Instantiated   package for the   class of packages <br>
//!          MeshShape, MeshAlgo, and so on ... <br>
class BRepMesh  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 

//! call to incremental mesh. <br>
Standard_EXPORT static  void Mesh(const TopoDS_Shape& S,const Standard_Real d) ;





protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //

friend class BRepMesh_Vertex;
friend class BRepMesh_Edge;
friend class BRepMesh_Triangle;
friend class BRepMesh_ShapeTool;
friend class BRepMesh_GeomTool;
friend class BRepMesh_Delaun;
friend class BRepMesh_DataMapOfVertexInteger;
friend class BRepMesh_DataMapOfMeshVertexInteger;
friend class BRepMesh_DataMapOfIntegerFace;
friend class BRepMesh_ListOfVertex;
friend class BRepMesh_ListOfXY;
friend class BRepMesh_DataMapOfIntegerListOfXY;
friend class BRepMesh_VertexHasher;
friend class BRepMesh_IndexedMapOfVertex;
friend class BRepMesh_DataMapOfCouplePnt;
friend class BRepMesh_DataMapOfShapeReal;
friend class BRepMesh_BiPoint;
friend class BRepMesh_Array1OfBiPoint;
friend class BRepMesh_Discret;
friend class BRepMesh_FastDiscret;
friend class BRepMesh_Classifier;
friend class BRepMesh_SurfaceGrid;
friend class BRepMesh_DataMapOfShapeSurfaceGrid;
friend class BRepMesh_ListOfSurfaceGrid;
friend class BRepMesh_EdgeDiscret;
friend class BRepMesh_DataMapOfShapeEdgeDiscret;
friend class BRepMesh_IncrementalMesh;
friend class BRepMesh_NodeHasherOfDataStructureOfDelaun;
friend class BRepMesh_LinkHasherOfDataStructureOfDelaun;
friend class BRepMesh_ElemHasherOfDataStructureOfDelaun;
friend class BRepMesh_IndexedDataMapNodeOfIDMapOfNodeOfDataStructureOfDelaun;
friend class BRepMesh_IDMapOfNodeOfDataStructureOfDelaun;
friend class BRepMesh_IndexedDataMapNodeOfIDMapOfLinkOfDataStructureOfDelaun;
friend class BRepMesh_IDMapOfLinkOfDataStructureOfDelaun;
friend class BRepMesh_IndexedMapNodeOfIMapOfElementOfDataStructureOfDelaun;
friend class BRepMesh_IMapOfElementOfDataStructureOfDelaun;
friend class BRepMesh_SelectorOfDataStructureOfDelaun;
friend class BRepMesh_DataStructureOfDelaun;
friend class BRepMesh_ComparatorOfVertexOfDelaun;
friend class BRepMesh_ComparatorOfIndexedVertexOfDelaun;
friend class BRepMesh_Array1OfVertexOfDelaun;
friend class BRepMesh_HArray1OfVertexOfDelaun;
friend class BRepMesh_HeapSortVertexOfDelaun;
friend class BRepMesh_HeapSortIndexedVertexOfDelaun;
friend class BRepMesh_DataMapNodeOfDataMapOfVertexInteger;
friend class BRepMesh_DataMapIteratorOfDataMapOfVertexInteger;
friend class BRepMesh_DataMapNodeOfDataMapOfMeshVertexInteger;
friend class BRepMesh_DataMapIteratorOfDataMapOfMeshVertexInteger;
friend class BRepMesh_DataMapNodeOfDataMapOfIntegerFace;
friend class BRepMesh_DataMapIteratorOfDataMapOfIntegerFace;
friend class BRepMesh_ListNodeOfListOfVertex;
friend class BRepMesh_ListIteratorOfListOfVertex;
friend class BRepMesh_ListNodeOfListOfXY;
friend class BRepMesh_ListIteratorOfListOfXY;
friend class BRepMesh_DataMapNodeOfDataMapOfIntegerListOfXY;
friend class BRepMesh_DataMapIteratorOfDataMapOfIntegerListOfXY;
friend class BRepMesh_IndexedMapNodeOfIndexedMapOfVertex;
friend class BRepMesh_DataMapNodeOfDataMapOfCouplePnt;
friend class BRepMesh_DataMapIteratorOfDataMapOfCouplePnt;
friend class BRepMesh_DataMapNodeOfDataMapOfShapeReal;
friend class BRepMesh_DataMapIteratorOfDataMapOfShapeReal;
friend class BRepMesh_DataMapNodeOfDataMapOfShapeSurfaceGrid;
friend class BRepMesh_DataMapIteratorOfDataMapOfShapeSurfaceGrid;
friend class BRepMesh_ListNodeOfListOfSurfaceGrid;
friend class BRepMesh_ListIteratorOfListOfSurfaceGrid;
friend class BRepMesh_DataMapNodeOfDataMapOfShapeEdgeDiscret;
friend class BRepMesh_DataMapIteratorOfDataMapOfShapeEdgeDiscret;

};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
