// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_Geom_Plane_HeaderFile
#define _Handle_Geom_Plane_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_Geom_ElementarySurface_HeaderFile
#include <Handle_Geom_ElementarySurface.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(Geom_ElementarySurface);
class Geom_Plane;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(Geom_Plane);

class Handle(Geom_Plane) : public Handle(Geom_ElementarySurface) {
  public:
    Handle(Geom_Plane)():Handle(Geom_ElementarySurface)() {} 
    Handle(Geom_Plane)(const Handle(Geom_Plane)& aHandle) : Handle(Geom_ElementarySurface)(aHandle) 
     {
     }

    Handle(Geom_Plane)(const Geom_Plane* anItem) : Handle(Geom_ElementarySurface)((Geom_ElementarySurface *)anItem) 
     {
     }

    Handle(Geom_Plane)& operator=(const Handle(Geom_Plane)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(Geom_Plane)& operator=(const Geom_Plane* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    Geom_Plane* operator->() const
     {
      return (Geom_Plane *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(Geom_Plane)();
 
   Standard_EXPORT static const Handle(Geom_Plane) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
