// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_Geom2d_BezierCurve_HeaderFile
#define _Handle_Geom2d_BezierCurve_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_Geom2d_BoundedCurve_HeaderFile
#include <Handle_Geom2d_BoundedCurve.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(Geom2d_BoundedCurve);
class Geom2d_BezierCurve;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(Geom2d_BezierCurve);

class Handle(Geom2d_BezierCurve) : public Handle(Geom2d_BoundedCurve) {
  public:
    Handle(Geom2d_BezierCurve)():Handle(Geom2d_BoundedCurve)() {} 
    Handle(Geom2d_BezierCurve)(const Handle(Geom2d_BezierCurve)& aHandle) : Handle(Geom2d_BoundedCurve)(aHandle) 
     {
     }

    Handle(Geom2d_BezierCurve)(const Geom2d_BezierCurve* anItem) : Handle(Geom2d_BoundedCurve)((Geom2d_BoundedCurve *)anItem) 
     {
     }

    Handle(Geom2d_BezierCurve)& operator=(const Handle(Geom2d_BezierCurve)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(Geom2d_BezierCurve)& operator=(const Geom2d_BezierCurve* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    Geom2d_BezierCurve* operator->() const
     {
      return (Geom2d_BezierCurve *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(Geom2d_BezierCurve)();
 
   Standard_EXPORT static const Handle(Geom2d_BezierCurve) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
