// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_Geom_Ellipse_HeaderFile
#define _Handle_Geom_Ellipse_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_Geom_Conic_HeaderFile
#include <Handle_Geom_Conic.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(Geom_Conic);
class Geom_Ellipse;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(Geom_Ellipse);

class Handle(Geom_Ellipse) : public Handle(Geom_Conic) {
  public:
    Handle(Geom_Ellipse)():Handle(Geom_Conic)() {} 
    Handle(Geom_Ellipse)(const Handle(Geom_Ellipse)& aHandle) : Handle(Geom_Conic)(aHandle) 
     {
     }

    Handle(Geom_Ellipse)(const Geom_Ellipse* anItem) : Handle(Geom_Conic)((Geom_Conic *)anItem) 
     {
     }

    Handle(Geom_Ellipse)& operator=(const Handle(Geom_Ellipse)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(Geom_Ellipse)& operator=(const Geom_Ellipse* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    Geom_Ellipse* operator->() const
     {
      return (Geom_Ellipse *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(Geom_Ellipse)();
 
   Standard_EXPORT static const Handle(Geom_Ellipse) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
