// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_Geom_SurfaceOfLinearExtrusion_HeaderFile
#define _Handle_Geom_SurfaceOfLinearExtrusion_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_Geom_SweptSurface_HeaderFile
#include <Handle_Geom_SweptSurface.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(Geom_SweptSurface);
class Geom_SurfaceOfLinearExtrusion;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(Geom_SurfaceOfLinearExtrusion);

class Handle(Geom_SurfaceOfLinearExtrusion) : public Handle(Geom_SweptSurface) {
  public:
    Handle(Geom_SurfaceOfLinearExtrusion)():Handle(Geom_SweptSurface)() {} 
    Handle(Geom_SurfaceOfLinearExtrusion)(const Handle(Geom_SurfaceOfLinearExtrusion)& aHandle) : Handle(Geom_SweptSurface)(aHandle) 
     {
     }

    Handle(Geom_SurfaceOfLinearExtrusion)(const Geom_SurfaceOfLinearExtrusion* anItem) : Handle(Geom_SweptSurface)((Geom_SweptSurface *)anItem) 
     {
     }

    Handle(Geom_SurfaceOfLinearExtrusion)& operator=(const Handle(Geom_SurfaceOfLinearExtrusion)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(Geom_SurfaceOfLinearExtrusion)& operator=(const Geom_SurfaceOfLinearExtrusion* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    Geom_SurfaceOfLinearExtrusion* operator->() const
     {
      return (Geom_SurfaceOfLinearExtrusion *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(Geom_SurfaceOfLinearExtrusion)();
 
   Standard_EXPORT static const Handle(Geom_SurfaceOfLinearExtrusion) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
