// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_Standard_Type_HeaderFile
#define _Handle_Standard_Type_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_Standard_Transient_HeaderFile
#include <Handle_Standard_Transient.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(Standard_Transient);
class Standard_Type;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(Standard_Type);

class Handle(Standard_Type) : public Handle(Standard_Transient) {
  public:
    Handle(Standard_Type)():Handle(Standard_Transient)() {} 
    Handle(Standard_Type)(const Handle(Standard_Type)& aHandle) : Handle(Standard_Transient)(aHandle) 
     {
     }

    Handle(Standard_Type)(const Standard_Type* anItem) : Handle(Standard_Transient)((Standard_Transient *)anItem) 
     {
     }

    Handle(Standard_Type)& operator=(const Handle(Standard_Type)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(Standard_Type)& operator=(const Standard_Type* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    Standard_Type* operator->() const
     {
      return (Standard_Type *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(Standard_Type)();
 
   Standard_EXPORT static const Handle(Standard_Type) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
