// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_Geom_Surface_HeaderFile
#define _Handle_Geom_Surface_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_Geom_Geometry_HeaderFile
#include <Handle_Geom_Geometry.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(Geom_Geometry);
class Geom_Surface;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(Geom_Surface);

class Handle(Geom_Surface) : public Handle(Geom_Geometry) {
  public:
    Handle(Geom_Surface)():Handle(Geom_Geometry)() {} 
    Handle(Geom_Surface)(const Handle(Geom_Surface)& aHandle) : Handle(Geom_Geometry)(aHandle) 
     {
     }

    Handle(Geom_Surface)(const Geom_Surface* anItem) : Handle(Geom_Geometry)((Geom_Geometry *)anItem) 
     {
     }

    Handle(Geom_Surface)& operator=(const Handle(Geom_Surface)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(Geom_Surface)& operator=(const Geom_Surface* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    Geom_Surface* operator->() const
     {
      return (Geom_Surface *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(Geom_Surface)();
 
   Standard_EXPORT static const Handle(Geom_Surface) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
