// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_Geom_OffsetSurface_HeaderFile
#define _Handle_Geom_OffsetSurface_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_Geom_Surface_HeaderFile
#include <Handle_Geom_Surface.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(Geom_Surface);
class Geom_OffsetSurface;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(Geom_OffsetSurface);

class Handle(Geom_OffsetSurface) : public Handle(Geom_Surface) {
  public:
    Handle(Geom_OffsetSurface)():Handle(Geom_Surface)() {} 
    Handle(Geom_OffsetSurface)(const Handle(Geom_OffsetSurface)& aHandle) : Handle(Geom_Surface)(aHandle) 
     {
     }

    Handle(Geom_OffsetSurface)(const Geom_OffsetSurface* anItem) : Handle(Geom_Surface)((Geom_Surface *)anItem) 
     {
     }

    Handle(Geom_OffsetSurface)& operator=(const Handle(Geom_OffsetSurface)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(Geom_OffsetSurface)& operator=(const Geom_OffsetSurface* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    Geom_OffsetSurface* operator->() const
     {
      return (Geom_OffsetSurface *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(Geom_OffsetSurface)();
 
   Standard_EXPORT static const Handle(Geom_OffsetSurface) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
