// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_Standard_OutOfRange_HeaderFile
#define _Handle_Standard_OutOfRange_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_Standard_RangeError_HeaderFile
#include <Handle_Standard_RangeError.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(Standard_RangeError);
class Standard_OutOfRange;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(Standard_OutOfRange);

class Handle(Standard_OutOfRange) : public Handle(Standard_RangeError) {
  public:
    Handle(Standard_OutOfRange)():Handle(Standard_RangeError)() {} 
    Handle(Standard_OutOfRange)(const Handle(Standard_OutOfRange)& aHandle) : Handle(Standard_RangeError)(aHandle) 
     {
     }

    Handle(Standard_OutOfRange)(const Standard_OutOfRange* anItem) : Handle(Standard_RangeError)((Standard_RangeError *)anItem) 
     {
     }

    Handle(Standard_OutOfRange)& operator=(const Handle(Standard_OutOfRange)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(Standard_OutOfRange)& operator=(const Standard_OutOfRange* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    Standard_OutOfRange* operator->() const
     {
      return (Standard_OutOfRange *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(Standard_OutOfRange)();
 
   Standard_EXPORT static const Handle(Standard_OutOfRange) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
