// File generated by CPPExt (Exception)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Standard_DomainError_HeaderFile
#define _Standard_DomainError_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_Standard_DomainError_HeaderFile
#include <Handle_Standard_DomainError.hxx>
#endif

#ifndef _Standard_SStream_HeaderFile
#include <Standard_SStream.hxx>
#endif


#ifndef _Standard_Failure_HeaderFile
#include <Standard_Failure.hxx>
#endif


#if !defined No_Exception && !defined No_Standard_DomainError
#define Standard_DomainError_Raise_if(CONDITION,MESSAGE) \
  if (CONDITION) Standard_DomainError::Raise(MESSAGE);
#else
#define Standard_DomainError_Raise_if(CONDITION,MESSAGE)
#endif

class Standard_DomainError : public Standard_Failure {

#ifndef NO_CXX_EXCEPTION
 Standard_EXPORT virtual void Throw() const;
#endif
public:
 Standard_EXPORT Standard_DomainError():Standard_Failure(){}
 Standard_EXPORT Standard_DomainError(const Standard_CString AString):Standard_Failure(AString){}
 Standard_EXPORT static void Raise(const Standard_CString aMessage = "");
 Standard_EXPORT static void Raise(Standard_SStream& aReason);
 Standard_EXPORT static Handle(Standard_DomainError) NewInstance(const Standard_CString aMessage); 

// Standard_EXPORT ~Standard_DomainError();

 // Type methods
 //
 Standard_EXPORT friend Handle_Standard_Type& Standard_DomainError_Type_();
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;			
// Standard_EXPORT Standard_Boolean             IsKind(const Handle(Standard_Type)&) const;
};

#endif
